FROM centos:latest

RUN dnf -y --disablerepo '*' --enablerepo extras swap centos-linux-repos centos-stream-repos
RUN dnf -y distro-sync

RUN yum install -y openssl

COPY gencerts.sh /

ENTRYPOINT [ "/gencerts.sh" ]
