// Code generated by protoc-gen-go. DO NOT EDIT.
// source: arke.proto

package arke

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Address_TargetType int32

const (
	Address_QUEUE  Address_TargetType = 0
	Address_TOPIC  Address_TargetType = 1
	Address_FILTER Address_TargetType = 2
)

var Address_TargetType_name = map[int32]string{
	0: "QUEUE",
	1: "TOPIC",
	2: "FILTER",
}

var Address_TargetType_value = map[string]int32{
	"QUEUE":  0,
	"TOPIC":  1,
	"FILTER": 2,
}

func (x Address_TargetType) String() string {
	return proto.EnumName(Address_TargetType_name, int32(x))
}

func (Address_TargetType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_84d488ad9203e158, []int{5, 0}
}

type Filter_MatchType int32

const (
	Filter_ALL Filter_MatchType = 0
	Filter_ANY Filter_MatchType = 1
)

var Filter_MatchType_name = map[int32]string{
	0: "ALL",
	1: "ANY",
}

var Filter_MatchType_value = map[string]int32{
	"ALL": 0,
	"ANY": 1,
}

func (x Filter_MatchType) String() string {
	return proto.EnumName(Filter_MatchType_name, int32(x))
}

func (Filter_MatchType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_84d488ad9203e158, []int{7, 0}
}

//*
// Represents the broker connection information. This is passed
// in by the client allowing us to remain a proxy, but also
// allowing us to support multiple providers at once such as
// RabbitMQ and Kafka.
type ConnectionConfiguration struct {
	Host                 string       `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port                 int32        `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Provider             string       `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	Tenant               string       `protobuf:"bytes,4,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Credentials          *Credentials `protobuf:"bytes,5,opt,name=credentials,proto3" json:"credentials,omitempty"`
	PrefetchCount        int32        `protobuf:"varint,6,opt,name=prefetch_count,json=prefetchCount,proto3" json:"prefetch_count,omitempty"`
	CaCertificate        []byte       `protobuf:"bytes,7,opt,name=ca_certificate,json=caCertificate,proto3" json:"ca_certificate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ConnectionConfiguration) Reset()         { *m = ConnectionConfiguration{} }
func (m *ConnectionConfiguration) String() string { return proto.CompactTextString(m) }
func (*ConnectionConfiguration) ProtoMessage()    {}
func (*ConnectionConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_84d488ad9203e158, []int{0}
}

func (m *ConnectionConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionConfiguration.Unmarshal(m, b)
}
func (m *ConnectionConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionConfiguration.Marshal(b, m, deterministic)
}
func (m *ConnectionConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionConfiguration.Merge(m, src)
}
func (m *ConnectionConfiguration) XXX_Size() int {
	return xxx_messageInfo_ConnectionConfiguration.Size(m)
}
func (m *ConnectionConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionConfiguration proto.InternalMessageInfo

func (m *ConnectionConfiguration) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *ConnectionConfiguration) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *ConnectionConfiguration) GetProvider() string {
	if m != nil {
		return m.Provider
	}
	return ""
}

func (m *ConnectionConfiguration) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

func (m *ConnectionConfiguration) GetCredentials() *Credentials {
	if m != nil {
		return m.Credentials
	}
	return nil
}

func (m *ConnectionConfiguration) GetPrefetchCount() int32 {
	if m != nil {
		return m.PrefetchCount
	}
	return 0
}

func (m *ConnectionConfiguration) GetCaCertificate() []byte {
	if m != nil {
		return m.CaCertificate
	}
	return nil
}

//*
// Represents the broker authentication information.
type Credentials struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Credentials) Reset()         { *m = Credentials{} }
func (m *Credentials) String() string { return proto.CompactTextString(m) }
func (*Credentials) ProtoMessage()    {}
func (*Credentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_84d488ad9203e158, []int{1}
}

func (m *Credentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Credentials.Unmarshal(m, b)
}
func (m *Credentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Credentials.Marshal(b, m, deterministic)
}
func (m *Credentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Credentials.Merge(m, src)
}
func (m *Credentials) XXX_Size() int {
	return xxx_messageInfo_Credentials.Size(m)
}
func (m *Credentials) XXX_DiscardUnknown() {
	xxx_messageInfo_Credentials.DiscardUnknown(m)
}

var xxx_messageInfo_Credentials proto.InternalMessageInfo

func (m *Credentials) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Credentials) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

//*
// Represents the connection response
type ConnectResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectResponse) Reset()         { *m = ConnectResponse{} }
func (m *ConnectResponse) String() string { return proto.CompactTextString(m) }
func (*ConnectResponse) ProtoMessage()    {}
func (*ConnectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_84d488ad9203e158, []int{2}
}

func (m *ConnectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectResponse.Unmarshal(m, b)
}
func (m *ConnectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectResponse.Marshal(b, m, deterministic)
}
func (m *ConnectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectResponse.Merge(m, src)
}
func (m *ConnectResponse) XXX_Size() int {
	return xxx_messageInfo_ConnectResponse.Size(m)
}
func (m *ConnectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectResponse proto.InternalMessageInfo

func (m *ConnectResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *ConnectResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

//*
// Represents a message that is being produced or consumed. The
// error property is set by the proxy when an error occurs during
// the consumer process.
type Message struct {
	Uuid                 string            `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Headers              map[string]string `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body                 []byte            `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Address              *Address          `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Persistent           bool              `protobuf:"varint,5,opt,name=persistent,proto3" json:"persistent,omitempty"`
	Error                *Error            `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_84d488ad9203e158, []int{3}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *Message) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *Message) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Message) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Message) GetPersistent() bool {
	if m != nil {
		return m.Persistent
	}
	return false
}

func (m *Message) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

//*
// Represents the response from publishing a message.
type MessageResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageResponse) Reset()         { *m = MessageResponse{} }
func (m *MessageResponse) String() string { return proto.CompactTextString(m) }
func (*MessageResponse) ProtoMessage()    {}
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_84d488ad9203e158, []int{4}
}

func (m *MessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageResponse.Unmarshal(m, b)
}
func (m *MessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageResponse.Marshal(b, m, deterministic)
}
func (m *MessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageResponse.Merge(m, src)
}
func (m *MessageResponse) XXX_Size() int {
	return xxx_messageInfo_MessageResponse.Size(m)
}
func (m *MessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageResponse proto.InternalMessageInfo

func (m *MessageResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *MessageResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

//*
// Represents the publishing destination for a message.
type Address struct {
	Name                 string             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Subject              string             `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Type                 Address_TargetType `protobuf:"varint,3,opt,name=type,proto3,enum=arke.Address_TargetType" json:"type,omitempty"`
	Durable              bool               `protobuf:"varint,4,opt,name=durable,proto3" json:"durable,omitempty"`
	AutoDelete           bool               `protobuf:"varint,5,opt,name=auto_delete,json=autoDelete,proto3" json:"auto_delete,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_84d488ad9203e158, []int{5}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Address) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *Address) GetType() Address_TargetType {
	if m != nil {
		return m.Type
	}
	return Address_QUEUE
}

func (m *Address) GetDurable() bool {
	if m != nil {
		return m.Durable
	}
	return false
}

func (m *Address) GetAutoDelete() bool {
	if m != nil {
		return m.AutoDelete
	}
	return false
}

//*
// Represents the source for consumer subscriptions.
type Source struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address              *Address          `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Durable              bool              `protobuf:"varint,4,opt,name=durable,proto3" json:"durable,omitempty"`
	AutoDelete           bool              `protobuf:"varint,5,opt,name=auto_delete,json=autoDelete,proto3" json:"auto_delete,omitempty"`
	Filter               *Filter           `protobuf:"bytes,6,opt,name=filter,proto3" json:"filter,omitempty"`
	Options              map[string]string `protobuf:"bytes,7,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Source) Reset()         { *m = Source{} }
func (m *Source) String() string { return proto.CompactTextString(m) }
func (*Source) ProtoMessage()    {}
func (*Source) Descriptor() ([]byte, []int) {
	return fileDescriptor_84d488ad9203e158, []int{6}
}

func (m *Source) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Source.Unmarshal(m, b)
}
func (m *Source) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Source.Marshal(b, m, deterministic)
}
func (m *Source) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Source.Merge(m, src)
}
func (m *Source) XXX_Size() int {
	return xxx_messageInfo_Source.Size(m)
}
func (m *Source) XXX_DiscardUnknown() {
	xxx_messageInfo_Source.DiscardUnknown(m)
}

var xxx_messageInfo_Source proto.InternalMessageInfo

func (m *Source) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Source) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Source) GetDurable() bool {
	if m != nil {
		return m.Durable
	}
	return false
}

func (m *Source) GetAutoDelete() bool {
	if m != nil {
		return m.AutoDelete
	}
	return false
}

func (m *Source) GetFilter() *Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *Source) GetOptions() map[string]string {
	if m != nil {
		return m.Options
	}
	return nil
}

//*
// Represents a filter for Message.headers. The Filter will prevent a consumer
// from consuming all messages from a Source.
type Filter struct {
	Matches              []*Match         `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	Type                 Filter_MatchType `protobuf:"varint,2,opt,name=type,proto3,enum=arke.Filter_MatchType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Filter) Reset()         { *m = Filter{} }
func (m *Filter) String() string { return proto.CompactTextString(m) }
func (*Filter) ProtoMessage()    {}
func (*Filter) Descriptor() ([]byte, []int) {
	return fileDescriptor_84d488ad9203e158, []int{7}
}

func (m *Filter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Filter.Unmarshal(m, b)
}
func (m *Filter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Filter.Marshal(b, m, deterministic)
}
func (m *Filter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Filter.Merge(m, src)
}
func (m *Filter) XXX_Size() int {
	return xxx_messageInfo_Filter.Size(m)
}
func (m *Filter) XXX_DiscardUnknown() {
	xxx_messageInfo_Filter.DiscardUnknown(m)
}

var xxx_messageInfo_Filter proto.InternalMessageInfo

func (m *Filter) GetMatches() []*Match {
	if m != nil {
		return m.Matches
	}
	return nil
}

func (m *Filter) GetType() Filter_MatchType {
	if m != nil {
		return m.Type
	}
	return Filter_ALL
}

//*
// Represents the key/value match for Message.headers. Currently only an
// exact match is supported.
type Match struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Match) Reset()         { *m = Match{} }
func (m *Match) String() string { return proto.CompactTextString(m) }
func (*Match) ProtoMessage()    {}
func (*Match) Descriptor() ([]byte, []int) {
	return fileDescriptor_84d488ad9203e158, []int{8}
}

func (m *Match) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Match.Unmarshal(m, b)
}
func (m *Match) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Match.Marshal(b, m, deterministic)
}
func (m *Match) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Match.Merge(m, src)
}
func (m *Match) XXX_Size() int {
	return xxx_messageInfo_Match.Size(m)
}
func (m *Match) XXX_DiscardUnknown() {
	xxx_messageInfo_Match.DiscardUnknown(m)
}

var xxx_messageInfo_Match proto.InternalMessageInfo

func (m *Match) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Match) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

//*
// Represents the response from AckMessage.
type AckResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AckResponse) Reset()         { *m = AckResponse{} }
func (m *AckResponse) String() string { return proto.CompactTextString(m) }
func (*AckResponse) ProtoMessage()    {}
func (*AckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_84d488ad9203e158, []int{9}
}

func (m *AckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckResponse.Unmarshal(m, b)
}
func (m *AckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckResponse.Marshal(b, m, deterministic)
}
func (m *AckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckResponse.Merge(m, src)
}
func (m *AckResponse) XXX_Size() int {
	return xxx_messageInfo_AckResponse.Size(m)
}
func (m *AckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AckResponse proto.InternalMessageInfo

func (m *AckResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *AckResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

//*
// Represents the response from NackMessage.
type NackResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NackResponse) Reset()         { *m = NackResponse{} }
func (m *NackResponse) String() string { return proto.CompactTextString(m) }
func (*NackResponse) ProtoMessage()    {}
func (*NackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_84d488ad9203e158, []int{10}
}

func (m *NackResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NackResponse.Unmarshal(m, b)
}
func (m *NackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NackResponse.Marshal(b, m, deterministic)
}
func (m *NackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NackResponse.Merge(m, src)
}
func (m *NackResponse) XXX_Size() int {
	return xxx_messageInfo_NackResponse.Size(m)
}
func (m *NackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NackResponse proto.InternalMessageInfo

func (m *NackResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *NackResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

//*
// No parameters or return value.
type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_84d488ad9203e158, []int{11}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

//*
// Represents a generic error message.
type Error struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	IsFatal              bool     `protobuf:"varint,3,opt,name=is_fatal,json=isFatal,proto3" json:"is_fatal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_84d488ad9203e158, []int{12}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetIsFatal() bool {
	if m != nil {
		return m.IsFatal
	}
	return false
}

func init() {
	proto.RegisterEnum("arke.Address_TargetType", Address_TargetType_name, Address_TargetType_value)
	proto.RegisterEnum("arke.Filter_MatchType", Filter_MatchType_name, Filter_MatchType_value)
	proto.RegisterType((*ConnectionConfiguration)(nil), "arke.ConnectionConfiguration")
	proto.RegisterType((*Credentials)(nil), "arke.Credentials")
	proto.RegisterType((*ConnectResponse)(nil), "arke.ConnectResponse")
	proto.RegisterType((*Message)(nil), "arke.Message")
	proto.RegisterMapType((map[string]string)(nil), "arke.Message.HeadersEntry")
	proto.RegisterType((*MessageResponse)(nil), "arke.MessageResponse")
	proto.RegisterType((*Address)(nil), "arke.Address")
	proto.RegisterType((*Source)(nil), "arke.Source")
	proto.RegisterMapType((map[string]string)(nil), "arke.Source.OptionsEntry")
	proto.RegisterType((*Filter)(nil), "arke.Filter")
	proto.RegisterType((*Match)(nil), "arke.Match")
	proto.RegisterType((*AckResponse)(nil), "arke.AckResponse")
	proto.RegisterType((*NackResponse)(nil), "arke.NackResponse")
	proto.RegisterType((*Empty)(nil), "arke.Empty")
	proto.RegisterType((*Error)(nil), "arke.Error")
}

func init() { proto.RegisterFile("arke.proto", fileDescriptor_84d488ad9203e158) }

var fileDescriptor_84d488ad9203e158 = []byte{
	// 897 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x5f, 0x6f, 0xe3, 0x44,
	0x10, 0x8f, 0xf3, 0xcf, 0xee, 0x38, 0x3d, 0xc2, 0x0a, 0x8a, 0x2f, 0xd2, 0x41, 0xb0, 0x38, 0x11,
	0xa1, 0x53, 0x54, 0x52, 0x90, 0xd0, 0xbd, 0xe5, 0x72, 0xa9, 0x38, 0xe8, 0xf5, 0x82, 0xdb, 0x7b,
	0xe0, 0xa9, 0xda, 0xac, 0x27, 0x8d, 0x49, 0xe2, 0xb5, 0x76, 0xd7, 0x87, 0xc2, 0x57, 0xe0, 0x81,
	0x47, 0xbe, 0x16, 0x5f, 0x82, 0xef, 0xc0, 0x23, 0xda, 0xf5, 0xba, 0x71, 0x51, 0x8b, 0x0a, 0xca,
	0xdb, 0xcc, 0x6f, 0x66, 0x27, 0xf3, 0xfb, 0xcd, 0x64, 0xd7, 0x00, 0x54, 0xac, 0x70, 0x98, 0x09,
	0xae, 0x38, 0x69, 0x6a, 0x3b, 0xfc, 0xcb, 0x81, 0x8f, 0x26, 0x3c, 0x4d, 0x91, 0xa9, 0x84, 0xa7,
	0x13, 0x9e, 0x2e, 0x92, 0xeb, 0x5c, 0x50, 0xed, 0x10, 0x02, 0xcd, 0x25, 0x97, 0x2a, 0x70, 0xfa,
	0xce, 0xe0, 0x20, 0x32, 0xb6, 0xc6, 0x32, 0x2e, 0x54, 0x50, 0xef, 0x3b, 0x83, 0x56, 0x64, 0x6c,
	0xd2, 0x03, 0x2f, 0x13, 0xfc, 0x5d, 0x12, 0xa3, 0x08, 0x1a, 0x26, 0xf7, 0xc6, 0x27, 0x47, 0xd0,
	0x56, 0x98, 0xd2, 0x54, 0x05, 0x4d, 0x13, 0xb1, 0x1e, 0x39, 0x01, 0x9f, 0x09, 0x8c, 0x31, 0x55,
	0x09, 0x5d, 0xcb, 0xa0, 0xd5, 0x77, 0x06, 0xfe, 0xe8, 0xfd, 0xa1, 0xe9, 0x6f, 0xb2, 0x0b, 0x44,
	0xd5, 0x2c, 0xf2, 0x14, 0x1e, 0x65, 0x02, 0x17, 0xa8, 0xd8, 0xf2, 0x8a, 0xf1, 0x3c, 0x55, 0x41,
	0xdb, 0xb4, 0x71, 0x58, 0xa2, 0x13, 0x0d, 0xea, 0x34, 0x46, 0xaf, 0x18, 0x0a, 0x95, 0x2c, 0x12,
	0x46, 0x15, 0x06, 0x6e, 0xdf, 0x19, 0x74, 0xa2, 0x43, 0x46, 0x27, 0x3b, 0x30, 0x9c, 0x82, 0x5f,
	0xf9, 0x25, 0xcd, 0x22, 0x97, 0x28, 0x52, 0xba, 0x41, 0xcb, 0xf8, 0xc6, 0x37, 0x0c, 0xa9, 0x94,
	0x3f, 0x73, 0x11, 0x1b, 0xe6, 0x9a, 0xa1, 0xf5, 0xc3, 0x73, 0x78, 0xcf, 0x0a, 0x18, 0xa1, 0xcc,
	0x78, 0x2a, 0x91, 0x04, 0xe0, 0xca, 0x9c, 0x31, 0x94, 0xd2, 0x54, 0xf2, 0xa2, 0xd2, 0x25, 0x9f,
	0x42, 0x0b, 0x85, 0xe0, 0xc2, 0x54, 0xf1, 0x47, 0x7e, 0x41, 0x78, 0xaa, 0xa1, 0xa8, 0x88, 0x84,
	0xbf, 0xd5, 0xc1, 0x7d, 0x8d, 0x52, 0xd2, 0x6b, 0xd4, 0x6a, 0xe7, 0x79, 0x12, 0x97, 0x13, 0xd0,
	0x36, 0xf9, 0x0a, 0xdc, 0x25, 0xd2, 0x18, 0x85, 0x0c, 0xea, 0xfd, 0xc6, 0xc0, 0x1f, 0xf5, 0x8a,
	0x22, 0xf6, 0xcc, 0xf0, 0xdb, 0x22, 0x38, 0x4d, 0x95, 0xd8, 0x46, 0x65, 0xaa, 0xae, 0x34, 0xe7,
	0xf1, 0xd6, 0xcc, 0xa7, 0x13, 0x19, 0x9b, 0x7c, 0x0e, 0x2e, 0x8d, 0x63, 0xa1, 0xdb, 0x6c, 0x9a,
	0x76, 0x0e, 0x8b, 0x4a, 0xe3, 0x02, 0x8c, 0xca, 0x28, 0xf9, 0x18, 0x20, 0x43, 0x21, 0x13, 0xa9,
	0x30, 0x55, 0x66, 0x56, 0x5e, 0x54, 0x41, 0x76, 0xac, 0xda, 0xf7, 0xb1, 0xea, 0x3d, 0x87, 0x4e,
	0xb5, 0x31, 0xd2, 0x85, 0xc6, 0x0a, 0xb7, 0x96, 0x98, 0x36, 0xc9, 0x07, 0xd0, 0x7a, 0x47, 0xd7,
	0x39, 0x5a, 0x81, 0x0b, 0xe7, 0x79, 0xfd, 0x1b, 0x47, 0x2b, 0x6c, 0xc9, 0xed, 0x47, 0xe1, 0x3f,
	0x1c, 0x70, 0x2d, 0x47, 0xad, 0x4b, 0x65, 0xe2, 0xc6, 0x2e, 0x8a, 0xcf, 0x7f, 0x42, 0xa6, 0x6c,
	0x2f, 0xa5, 0x4b, 0x9e, 0x41, 0x53, 0x6d, 0x33, 0x34, 0x2a, 0x3e, 0x1a, 0x05, 0xb7, 0xe4, 0x1a,
	0x5e, 0x52, 0x71, 0x8d, 0xea, 0x72, 0x9b, 0x61, 0x64, 0xb2, 0x74, 0x9d, 0x38, 0x17, 0x74, 0xbe,
	0x46, 0xa3, 0xaf, 0x17, 0x95, 0x2e, 0xf9, 0x04, 0x7c, 0x9a, 0x2b, 0x7e, 0x15, 0xe3, 0x1a, 0x15,
	0x96, 0x8a, 0x6a, 0xe8, 0xa5, 0x41, 0xc2, 0x21, 0xc0, 0xae, 0x1c, 0x39, 0x80, 0xd6, 0x0f, 0x6f,
	0xa7, 0x6f, 0xa7, 0xdd, 0x9a, 0x36, 0x2f, 0xdf, 0xcc, 0x5e, 0x4d, 0xba, 0x0e, 0x01, 0x68, 0x9f,
	0xbe, 0x3a, 0xbb, 0x9c, 0x46, 0xdd, 0x7a, 0xf8, 0x7b, 0x1d, 0xda, 0x17, 0x3c, 0x17, 0x0c, 0xef,
	0x64, 0x54, 0x99, 0x74, 0xe3, 0x5f, 0x27, 0xfd, 0xff, 0x5b, 0x26, 0x9f, 0x41, 0x7b, 0x91, 0xac,
	0x15, 0x96, 0x5b, 0xd0, 0x29, 0x7e, 0xe2, 0xd4, 0x60, 0x91, 0x8d, 0x91, 0x13, 0x70, 0x79, 0xa6,
	0x6f, 0x17, 0x19, 0xb8, 0x66, 0x7b, 0x1f, 0x17, 0x69, 0x45, 0xf3, 0xc3, 0x37, 0x45, 0xcc, 0x2e,
	0xaf, 0xcd, 0xd4, 0xcb, 0x53, 0x0d, 0xfc, 0xa7, 0xe5, 0xf9, 0x05, 0xda, 0x45, 0x0b, 0xe4, 0x29,
	0xb8, 0x1b, 0xaa, 0xd8, 0x12, 0xf5, 0xce, 0x34, 0x76, 0xbb, 0xf1, 0x5a, 0x83, 0x51, 0x19, 0x23,
	0x5f, 0xd8, 0x19, 0xd7, 0xcd, 0x8c, 0x8f, 0xaa, 0x2c, 0x8a, 0xd4, 0xdd, 0x84, 0xc3, 0x27, 0x70,
	0x70, 0x03, 0x11, 0x17, 0x1a, 0xe3, 0xb3, 0xb3, 0x6e, 0xcd, 0x18, 0xe7, 0x3f, 0x76, 0x9d, 0xf0,
	0x4b, 0x68, 0x99, 0xf0, 0x9d, 0x33, 0xb9, 0xb3, 0xe5, 0xf0, 0x3b, 0xf0, 0xc7, 0x6c, 0xb5, 0x9f,
	0x3d, 0xff, 0x1e, 0x3a, 0xe7, 0x74, 0x5f, 0xc5, 0x5c, 0x68, 0x4d, 0x37, 0x99, 0xda, 0x86, 0x33,
	0x68, 0x99, 0x80, 0x2e, 0xb7, 0x29, 0xfe, 0x96, 0x96, 0x57, 0xe9, 0x6a, 0xba, 0x8c, 0xc7, 0x58,
	0x3e, 0x12, 0xda, 0x26, 0x8f, 0xc1, 0x4b, 0xe4, 0xd5, 0x82, 0x2a, 0xba, 0x36, 0x3b, 0xe8, 0x45,
	0x6e, 0x22, 0x4f, 0xb5, 0x3b, 0xfa, 0xd3, 0x01, 0x6f, 0x26, 0x78, 0x9c, 0x33, 0x14, 0x64, 0x0c,
	0xae, 0xbd, 0x4e, 0xc9, 0x13, 0xfb, 0x1c, 0xdc, 0xfd, 0x3c, 0xf5, 0x3e, 0xbc, 0x15, 0x2e, 0x59,
	0x86, 0x35, 0xf2, 0x35, 0xf8, 0x17, 0x98, 0xc6, 0xe5, 0x25, 0x7a, 0x78, 0xeb, 0x7e, 0x2c, 0x8f,
	0xfd, 0xe3, 0x46, 0x31, 0xc7, 0xdc, 0x59, 0x3e, 0x5f, 0x27, 0x72, 0xf9, 0xd0, 0x23, 0x03, 0xe7,
	0xd8, 0x21, 0x03, 0x80, 0x97, 0x89, 0x64, 0xb6, 0xe7, 0x52, 0x3a, 0x2d, 0x55, 0xaf, 0xea, 0x84,
	0xb5, 0xd1, 0xaf, 0x75, 0xf0, 0x26, 0x3c, 0x95, 0xf9, 0x66, 0x3f, 0x3c, 0x9f, 0xc1, 0xc1, 0x45,
	0x3e, 0x97, 0x4c, 0x24, 0x73, 0x24, 0x9d, 0xea, 0xff, 0xa8, 0x77, 0x9b, 0x40, 0x58, 0x3b, 0x76,
	0xc8, 0x31, 0xc0, 0x98, 0xad, 0xee, 0x11, 0xc5, 0xbe, 0xbc, 0x95, 0xd5, 0x0b, 0x6b, 0x64, 0x04,
	0xbe, 0xde, 0x9f, 0x7b, 0x8e, 0x90, 0xc2, 0xad, 0x6e, 0x58, 0x58, 0x7b, 0xb8, 0x1a, 0x2f, 0x8e,
	0xc0, 0xe3, 0xe2, 0xda, 0x60, 0x2f, 0x60, 0x2c, 0x56, 0x38, 0xd3, 0x9f, 0x25, 0x72, 0xde, 0x36,
	0x9f, 0x27, 0x27, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0x8f, 0x46, 0x15, 0x11, 0xac, 0x08, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProducerClient is the client API for Producer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProducerClient interface {
	// Connect to a message broker. Pass in a ConnectionConfiguration with broker
	// specific connection information.
	Connect(ctx context.Context, in *ConnectionConfiguration, opts ...grpc.CallOption) (*ConnectResponse, error)
	// Send a single message to the message broker.
	SendMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*MessageResponse, error)
	// Send messages to the message broker.
	Publish(ctx context.Context, opts ...grpc.CallOption) (Producer_PublishClient, error)
	// Disconnect from the proxy and the message broker.
	Disconnect(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type producerClient struct {
	cc *grpc.ClientConn
}

func NewProducerClient(cc *grpc.ClientConn) ProducerClient {
	return &producerClient{cc}
}

func (c *producerClient) Connect(ctx context.Context, in *ConnectionConfiguration, opts ...grpc.CallOption) (*ConnectResponse, error) {
	out := new(ConnectResponse)
	err := c.cc.Invoke(ctx, "/arke.Producer/Connect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *producerClient) SendMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*MessageResponse, error) {
	out := new(MessageResponse)
	err := c.cc.Invoke(ctx, "/arke.Producer/SendMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *producerClient) Publish(ctx context.Context, opts ...grpc.CallOption) (Producer_PublishClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Producer_serviceDesc.Streams[0], "/arke.Producer/Publish", opts...)
	if err != nil {
		return nil, err
	}
	x := &producerPublishClient{stream}
	return x, nil
}

type Producer_PublishClient interface {
	Send(*Message) error
	Recv() (*MessageResponse, error)
	grpc.ClientStream
}

type producerPublishClient struct {
	grpc.ClientStream
}

func (x *producerPublishClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *producerPublishClient) Recv() (*MessageResponse, error) {
	m := new(MessageResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *producerClient) Disconnect(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/arke.Producer/Disconnect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProducerServer is the server API for Producer service.
type ProducerServer interface {
	// Connect to a message broker. Pass in a ConnectionConfiguration with broker
	// specific connection information.
	Connect(context.Context, *ConnectionConfiguration) (*ConnectResponse, error)
	// Send a single message to the message broker.
	SendMessage(context.Context, *Message) (*MessageResponse, error)
	// Send messages to the message broker.
	Publish(Producer_PublishServer) error
	// Disconnect from the proxy and the message broker.
	Disconnect(context.Context, *Empty) (*Empty, error)
}

// UnimplementedProducerServer can be embedded to have forward compatible implementations.
type UnimplementedProducerServer struct {
}

func (*UnimplementedProducerServer) Connect(ctx context.Context, req *ConnectionConfiguration) (*ConnectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (*UnimplementedProducerServer) SendMessage(ctx context.Context, req *Message) (*MessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMessage not implemented")
}
func (*UnimplementedProducerServer) Publish(srv Producer_PublishServer) error {
	return status.Errorf(codes.Unimplemented, "method Publish not implemented")
}
func (*UnimplementedProducerServer) Disconnect(ctx context.Context, req *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Disconnect not implemented")
}

func RegisterProducerServer(s *grpc.Server, srv ProducerServer) {
	s.RegisterService(&_Producer_serviceDesc, srv)
}

func _Producer_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectionConfiguration)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProducerServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/arke.Producer/Connect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProducerServer).Connect(ctx, req.(*ConnectionConfiguration))
	}
	return interceptor(ctx, in, info, handler)
}

func _Producer_SendMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProducerServer).SendMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/arke.Producer/SendMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProducerServer).SendMessage(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _Producer_Publish_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProducerServer).Publish(&producerPublishServer{stream})
}

type Producer_PublishServer interface {
	Send(*MessageResponse) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type producerPublishServer struct {
	grpc.ServerStream
}

func (x *producerPublishServer) Send(m *MessageResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *producerPublishServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Producer_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProducerServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/arke.Producer/Disconnect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProducerServer).Disconnect(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Producer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "arke.Producer",
	HandlerType: (*ProducerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Connect",
			Handler:    _Producer_Connect_Handler,
		},
		{
			MethodName: "SendMessage",
			Handler:    _Producer_SendMessage_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _Producer_Disconnect_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Publish",
			Handler:       _Producer_Publish_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "arke.proto",
}

// ConsumerClient is the client API for Consumer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConsumerClient interface {
	// Connect to a message broker. Pass in a ConnectionConfiguration with broker
	// specific connection information.
	Connect(ctx context.Context, in *ConnectionConfiguration, opts ...grpc.CallOption) (*ConnectResponse, error)
	// Subscribe to a message broker source and receive a stream of messages when they are available.
	Subscribe(ctx context.Context, in *Source, opts ...grpc.CallOption) (Consumer_SubscribeClient, error)
	// Ack a received message.
	AckMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*AckResponse, error)
	// Nack a received message.
	NackMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*NackResponse, error)
	// Disconnect from the proxy and the message broker.
	Disconnect(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type consumerClient struct {
	cc *grpc.ClientConn
}

func NewConsumerClient(cc *grpc.ClientConn) ConsumerClient {
	return &consumerClient{cc}
}

func (c *consumerClient) Connect(ctx context.Context, in *ConnectionConfiguration, opts ...grpc.CallOption) (*ConnectResponse, error) {
	out := new(ConnectResponse)
	err := c.cc.Invoke(ctx, "/arke.Consumer/Connect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consumerClient) Subscribe(ctx context.Context, in *Source, opts ...grpc.CallOption) (Consumer_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Consumer_serviceDesc.Streams[0], "/arke.Consumer/Subscribe", opts...)
	if err != nil {
		return nil, err
	}
	x := &consumerSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Consumer_SubscribeClient interface {
	Recv() (*Message, error)
	grpc.ClientStream
}

type consumerSubscribeClient struct {
	grpc.ClientStream
}

func (x *consumerSubscribeClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *consumerClient) AckMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*AckResponse, error) {
	out := new(AckResponse)
	err := c.cc.Invoke(ctx, "/arke.Consumer/AckMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consumerClient) NackMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*NackResponse, error) {
	out := new(NackResponse)
	err := c.cc.Invoke(ctx, "/arke.Consumer/NackMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consumerClient) Disconnect(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/arke.Consumer/Disconnect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConsumerServer is the server API for Consumer service.
type ConsumerServer interface {
	// Connect to a message broker. Pass in a ConnectionConfiguration with broker
	// specific connection information.
	Connect(context.Context, *ConnectionConfiguration) (*ConnectResponse, error)
	// Subscribe to a message broker source and receive a stream of messages when they are available.
	Subscribe(*Source, Consumer_SubscribeServer) error
	// Ack a received message.
	AckMessage(context.Context, *Message) (*AckResponse, error)
	// Nack a received message.
	NackMessage(context.Context, *Message) (*NackResponse, error)
	// Disconnect from the proxy and the message broker.
	Disconnect(context.Context, *Empty) (*Empty, error)
}

// UnimplementedConsumerServer can be embedded to have forward compatible implementations.
type UnimplementedConsumerServer struct {
}

func (*UnimplementedConsumerServer) Connect(ctx context.Context, req *ConnectionConfiguration) (*ConnectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (*UnimplementedConsumerServer) Subscribe(req *Source, srv Consumer_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (*UnimplementedConsumerServer) AckMessage(ctx context.Context, req *Message) (*AckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AckMessage not implemented")
}
func (*UnimplementedConsumerServer) NackMessage(ctx context.Context, req *Message) (*NackResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NackMessage not implemented")
}
func (*UnimplementedConsumerServer) Disconnect(ctx context.Context, req *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Disconnect not implemented")
}

func RegisterConsumerServer(s *grpc.Server, srv ConsumerServer) {
	s.RegisterService(&_Consumer_serviceDesc, srv)
}

func _Consumer_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectionConfiguration)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsumerServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/arke.Consumer/Connect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsumerServer).Connect(ctx, req.(*ConnectionConfiguration))
	}
	return interceptor(ctx, in, info, handler)
}

func _Consumer_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Source)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConsumerServer).Subscribe(m, &consumerSubscribeServer{stream})
}

type Consumer_SubscribeServer interface {
	Send(*Message) error
	grpc.ServerStream
}

type consumerSubscribeServer struct {
	grpc.ServerStream
}

func (x *consumerSubscribeServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func _Consumer_AckMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsumerServer).AckMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/arke.Consumer/AckMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsumerServer).AckMessage(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _Consumer_NackMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Message)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsumerServer).NackMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/arke.Consumer/NackMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsumerServer).NackMessage(ctx, req.(*Message))
	}
	return interceptor(ctx, in, info, handler)
}

func _Consumer_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsumerServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/arke.Consumer/Disconnect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsumerServer).Disconnect(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Consumer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "arke.Consumer",
	HandlerType: (*ConsumerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Connect",
			Handler:    _Consumer_Connect_Handler,
		},
		{
			MethodName: "AckMessage",
			Handler:    _Consumer_AckMessage_Handler,
		},
		{
			MethodName: "NackMessage",
			Handler:    _Consumer_NackMessage_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _Consumer_Disconnect_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _Consumer_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "arke.proto",
}
