// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: arke.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProducerClient is the client API for Producer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProducerClient interface {
	// Connect to a message broker. Pass in a ConnectionConfiguration with broker
	// specific connection information.
	Connect(ctx context.Context, in *ConnectionConfiguration, opts ...grpc.CallOption) (*ConnectResponse, error)
	// Send messages to the message broker.
	Publish(ctx context.Context, opts ...grpc.CallOption) (Producer_PublishClient, error)
	// Disconnect from the proxy and the message broker.
	Disconnect(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type producerClient struct {
	cc grpc.ClientConnInterface
}

func NewProducerClient(cc grpc.ClientConnInterface) ProducerClient {
	return &producerClient{cc}
}

func (c *producerClient) Connect(ctx context.Context, in *ConnectionConfiguration, opts ...grpc.CallOption) (*ConnectResponse, error) {
	out := new(ConnectResponse)
	err := c.cc.Invoke(ctx, "/arke.Producer/Connect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *producerClient) Publish(ctx context.Context, opts ...grpc.CallOption) (Producer_PublishClient, error) {
	stream, err := c.cc.NewStream(ctx, &Producer_ServiceDesc.Streams[0], "/arke.Producer/Publish", opts...)
	if err != nil {
		return nil, err
	}
	x := &producerPublishClient{stream}
	return x, nil
}

type Producer_PublishClient interface {
	Send(*Message) error
	Recv() (*MessageResponse, error)
	grpc.ClientStream
}

type producerPublishClient struct {
	grpc.ClientStream
}

func (x *producerPublishClient) Send(m *Message) error {
	return x.ClientStream.SendMsg(m)
}

func (x *producerPublishClient) Recv() (*MessageResponse, error) {
	m := new(MessageResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *producerClient) Disconnect(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/arke.Producer/Disconnect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProducerServer is the server API for Producer service.
// All implementations must embed UnimplementedProducerServer
// for forward compatibility
type ProducerServer interface {
	// Connect to a message broker. Pass in a ConnectionConfiguration with broker
	// specific connection information.
	Connect(context.Context, *ConnectionConfiguration) (*ConnectResponse, error)
	// Send messages to the message broker.
	Publish(Producer_PublishServer) error
	// Disconnect from the proxy and the message broker.
	Disconnect(context.Context, *Empty) (*Empty, error)
	mustEmbedUnimplementedProducerServer()
}

// UnimplementedProducerServer must be embedded to have forward compatible implementations.
type UnimplementedProducerServer struct {
}

func (UnimplementedProducerServer) Connect(context.Context, *ConnectionConfiguration) (*ConnectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedProducerServer) Publish(Producer_PublishServer) error {
	return status.Errorf(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedProducerServer) Disconnect(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Disconnect not implemented")
}
func (UnimplementedProducerServer) mustEmbedUnimplementedProducerServer() {}

// UnsafeProducerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProducerServer will
// result in compilation errors.
type UnsafeProducerServer interface {
	mustEmbedUnimplementedProducerServer()
}

func RegisterProducerServer(s grpc.ServiceRegistrar, srv ProducerServer) {
	s.RegisterService(&Producer_ServiceDesc, srv)
}

func _Producer_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectionConfiguration)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProducerServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/arke.Producer/Connect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProducerServer).Connect(ctx, req.(*ConnectionConfiguration))
	}
	return interceptor(ctx, in, info, handler)
}

func _Producer_Publish_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProducerServer).Publish(&producerPublishServer{stream})
}

type Producer_PublishServer interface {
	Send(*MessageResponse) error
	Recv() (*Message, error)
	grpc.ServerStream
}

type producerPublishServer struct {
	grpc.ServerStream
}

func (x *producerPublishServer) Send(m *MessageResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *producerPublishServer) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Producer_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProducerServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/arke.Producer/Disconnect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProducerServer).Disconnect(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Producer_ServiceDesc is the grpc.ServiceDesc for Producer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Producer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "arke.Producer",
	HandlerType: (*ProducerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Connect",
			Handler:    _Producer_Connect_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _Producer_Disconnect_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Publish",
			Handler:       _Producer_Publish_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "arke.proto",
}

// ConsumerClient is the client API for Consumer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConsumerClient interface {
	// Connect to a message broker. Pass in a ConnectionConfiguration with broker
	// specific connection information.
	Connect(ctx context.Context, in *ConnectionConfiguration, opts ...grpc.CallOption) (*ConnectResponse, error)
	// Subscribe to a message broker source and receive a stream of messages when they are available.
	Consume(ctx context.Context, opts ...grpc.CallOption) (Consumer_ConsumeClient, error)
	// Disconnect from the proxy and the message broker.
	Disconnect(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type consumerClient struct {
	cc grpc.ClientConnInterface
}

func NewConsumerClient(cc grpc.ClientConnInterface) ConsumerClient {
	return &consumerClient{cc}
}

func (c *consumerClient) Connect(ctx context.Context, in *ConnectionConfiguration, opts ...grpc.CallOption) (*ConnectResponse, error) {
	out := new(ConnectResponse)
	err := c.cc.Invoke(ctx, "/arke.Consumer/Connect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *consumerClient) Consume(ctx context.Context, opts ...grpc.CallOption) (Consumer_ConsumeClient, error) {
	stream, err := c.cc.NewStream(ctx, &Consumer_ServiceDesc.Streams[0], "/arke.Consumer/Consume", opts...)
	if err != nil {
		return nil, err
	}
	x := &consumerConsumeClient{stream}
	return x, nil
}

type Consumer_ConsumeClient interface {
	Send(*Consume) error
	Recv() (*ConsumeResponse, error)
	grpc.ClientStream
}

type consumerConsumeClient struct {
	grpc.ClientStream
}

func (x *consumerConsumeClient) Send(m *Consume) error {
	return x.ClientStream.SendMsg(m)
}

func (x *consumerConsumeClient) Recv() (*ConsumeResponse, error) {
	m := new(ConsumeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *consumerClient) Disconnect(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/arke.Consumer/Disconnect", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConsumerServer is the server API for Consumer service.
// All implementations must embed UnimplementedConsumerServer
// for forward compatibility
type ConsumerServer interface {
	// Connect to a message broker. Pass in a ConnectionConfiguration with broker
	// specific connection information.
	Connect(context.Context, *ConnectionConfiguration) (*ConnectResponse, error)
	// Subscribe to a message broker source and receive a stream of messages when they are available.
	Consume(Consumer_ConsumeServer) error
	// Disconnect from the proxy and the message broker.
	Disconnect(context.Context, *Empty) (*Empty, error)
	mustEmbedUnimplementedConsumerServer()
}

// UnimplementedConsumerServer must be embedded to have forward compatible implementations.
type UnimplementedConsumerServer struct {
}

func (UnimplementedConsumerServer) Connect(context.Context, *ConnectionConfiguration) (*ConnectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedConsumerServer) Consume(Consumer_ConsumeServer) error {
	return status.Errorf(codes.Unimplemented, "method Consume not implemented")
}
func (UnimplementedConsumerServer) Disconnect(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Disconnect not implemented")
}
func (UnimplementedConsumerServer) mustEmbedUnimplementedConsumerServer() {}

// UnsafeConsumerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConsumerServer will
// result in compilation errors.
type UnsafeConsumerServer interface {
	mustEmbedUnimplementedConsumerServer()
}

func RegisterConsumerServer(s grpc.ServiceRegistrar, srv ConsumerServer) {
	s.RegisterService(&Consumer_ServiceDesc, srv)
}

func _Consumer_Connect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectionConfiguration)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsumerServer).Connect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/arke.Consumer/Connect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsumerServer).Connect(ctx, req.(*ConnectionConfiguration))
	}
	return interceptor(ctx, in, info, handler)
}

func _Consumer_Consume_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ConsumerServer).Consume(&consumerConsumeServer{stream})
}

type Consumer_ConsumeServer interface {
	Send(*ConsumeResponse) error
	Recv() (*Consume, error)
	grpc.ServerStream
}

type consumerConsumeServer struct {
	grpc.ServerStream
}

func (x *consumerConsumeServer) Send(m *ConsumeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *consumerConsumeServer) Recv() (*Consume, error) {
	m := new(Consume)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Consumer_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConsumerServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/arke.Consumer/Disconnect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConsumerServer).Disconnect(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Consumer_ServiceDesc is the grpc.ServiceDesc for Consumer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Consumer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "arke.Consumer",
	HandlerType: (*ConsumerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Connect",
			Handler:    _Consumer_Connect_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _Consumer_Disconnect_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Consume",
			Handler:       _Consumer_Consume_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "arke.proto",
}

// HealthzClient is the client API for Healthz service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HealthzClient interface {
	Check(ctx context.Context, opts ...grpc.CallOption) (Healthz_CheckClient, error)
}

type healthzClient struct {
	cc grpc.ClientConnInterface
}

func NewHealthzClient(cc grpc.ClientConnInterface) HealthzClient {
	return &healthzClient{cc}
}

func (c *healthzClient) Check(ctx context.Context, opts ...grpc.CallOption) (Healthz_CheckClient, error) {
	stream, err := c.cc.NewStream(ctx, &Healthz_ServiceDesc.Streams[0], "/arke.Healthz/Check", opts...)
	if err != nil {
		return nil, err
	}
	x := &healthzCheckClient{stream}
	return x, nil
}

type Healthz_CheckClient interface {
	Send(*Health) error
	Recv() (*Health, error)
	grpc.ClientStream
}

type healthzCheckClient struct {
	grpc.ClientStream
}

func (x *healthzCheckClient) Send(m *Health) error {
	return x.ClientStream.SendMsg(m)
}

func (x *healthzCheckClient) Recv() (*Health, error) {
	m := new(Health)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// HealthzServer is the server API for Healthz service.
// All implementations must embed UnimplementedHealthzServer
// for forward compatibility
type HealthzServer interface {
	Check(Healthz_CheckServer) error
	mustEmbedUnimplementedHealthzServer()
}

// UnimplementedHealthzServer must be embedded to have forward compatible implementations.
type UnimplementedHealthzServer struct {
}

func (UnimplementedHealthzServer) Check(Healthz_CheckServer) error {
	return status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedHealthzServer) mustEmbedUnimplementedHealthzServer() {}

// UnsafeHealthzServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HealthzServer will
// result in compilation errors.
type UnsafeHealthzServer interface {
	mustEmbedUnimplementedHealthzServer()
}

func RegisterHealthzServer(s grpc.ServiceRegistrar, srv HealthzServer) {
	s.RegisterService(&Healthz_ServiceDesc, srv)
}

func _Healthz_Check_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HealthzServer).Check(&healthzCheckServer{stream})
}

type Healthz_CheckServer interface {
	Send(*Health) error
	Recv() (*Health, error)
	grpc.ServerStream
}

type healthzCheckServer struct {
	grpc.ServerStream
}

func (x *healthzCheckServer) Send(m *Health) error {
	return x.ServerStream.SendMsg(m)
}

func (x *healthzCheckServer) Recv() (*Health, error) {
	m := new(Health)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Healthz_ServiceDesc is the grpc.ServiceDesc for Healthz service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Healthz_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "arke.Healthz",
	HandlerType: (*HealthzServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Check",
			Handler:       _Healthz_Check_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "arke.proto",
}
